package eu.tvato.lempie.database.theme

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "theme")
data class Theme(
    @PrimaryKey(true) val id: Int = 0,
    @ColumnInfo("theme_name") val themeName: String,
    @ColumnInfo("primary") val primary: Long = 0xFFFF0000,
    @ColumnInfo("onPrimary") val onPrimary: Long = 0xFFFFFFFF,
    @ColumnInfo("primaryContainer") val primaryContainer: Long = 0xFF000000,
    @ColumnInfo("onPrimaryContainer") val onPrimaryContainer: Long = 0xFFFFFFFF,
    @ColumnInfo("inversePrimary") val inversePrimary: Long = 0xFFFFFFFF,
    @ColumnInfo("secondary") val secondary: Long = 0xFFFF9800,
    @ColumnInfo("onSecondary") val onSecondary: Long = 0xFFFFFFFF,
    @ColumnInfo("secondaryContainer") val secondaryContainer: Long = 0xFF333333,
    @ColumnInfo("onSecondaryContainer") val onSecondaryContainer: Long = 0xFFFFFFFF,
    @ColumnInfo("tertiary") val tertiary: Long = 0xFF555555,
    @ColumnInfo("onTertiary") val onTertiary: Long = 0xFFFFFFFF,
    @ColumnInfo("tertiaryContainer") val tertiaryContainer: Long = 0xFFFFC107,
    @ColumnInfo("onTertiaryContainer") val onTertiaryContainer: Long = 0xFF000000,
    @ColumnInfo("background") val background: Long = 0xFF000000,
    @ColumnInfo("onBackground") val onBackground: Long = 0xFFFFFFFF,
    @ColumnInfo("surface") val surface: Long = 0xFF181818,
    @ColumnInfo("onSurface") val onSurface: Long = 0xFFFFFFFF,
    @ColumnInfo("surfaceVariant") val surfaceVariant: Long = 0xFFEA5050,
    @ColumnInfo("onSurfaceVariant") val onSurfaceVariant: Long = 0xFFF0F0F0,
    @ColumnInfo("surfaceTint") val surfaceTint: Long = 0xFF000000,
    @ColumnInfo("inverseSurface") val inverseSurface: Long = 0xFFFFFFFF,
    @ColumnInfo("inverseOnSurface") val inverseOnSurface: Long = 0xFF8F8F8F,
    @ColumnInfo("error") val error: Long = 0xFFFF0000,
    @ColumnInfo("onError") val onError: Long = 0xFFFFFFFF,
    @ColumnInfo("errorContainer") val errorContainer: Long = 0xFF000000,
    @ColumnInfo("onErrorContainer") val onErrorContainer: Long = 0xFFFFFFFF,
    @ColumnInfo("outline") val outline: Long = 0xFF880000,
    @ColumnInfo("outlineVariant") val outlineVariant: Long = 0xFFF08500,
    @ColumnInfo("scrim") val scrim: Long = 0x44FF0000,
    @ColumnInfo("surfaceBright") val surfaceBright: Long = 0xFF505050,
    @ColumnInfo("surfaceContainer") val surfaceContainer: Long = 0xFF303030,
    @ColumnInfo("surfaceContainerHigh") val surfaceContainerHigh: Long = 0xFF505050,
    @ColumnInfo("surfaceContainerHighest") val surfaceContainerHighest: Long = 0xFF535353,
    @ColumnInfo("surfaceContainerLow") val surfaceContainerLow: Long = 0xFF121212,
    @ColumnInfo("surfaceContainerLowest") val surfaceContainerLowest: Long = 0xFF050505,
    @ColumnInfo("surfaceDim") val surfaceDim: Long = 0xFF000000,
    @ColumnInfo("primaryFixed") val primaryFixed: Long = 0xFF050505,
    @ColumnInfo("primaryFixedDim") val primaryFixedDim: Long = 0xFF000000,
    @ColumnInfo("onPrimaryFixed") val onPrimaryFixed: Long = 0xFFFFFFFF,
    @ColumnInfo("onPrimaryFixedVariant") val onPrimaryFixedVariant: Long = 0xFFF0F0F0,
    @ColumnInfo("secondaryFixed") val secondaryFixed: Long = 0xFF303030,
    @ColumnInfo("secondaryFixedDim") val secondaryFixedDim: Long = 0xFF060606,
    @ColumnInfo("onSecondaryFixed") val onSecondaryFixed: Long = 0xFFFFFFFF,
    @ColumnInfo("onSecondaryFixedVariant") val onSecondaryFixedVariant: Long = 0xFFF0F0F0,
    @ColumnInfo("tertiaryFixed") val tertiaryFixed: Long = 0xFF5F5F5F,
    @ColumnInfo("tertiaryFixedDim") val tertiaryFixedDim: Long = 0xFF353535,
    @ColumnInfo("onTertiaryFixed") val onTertiaryFixed: Long = 0xFFFFFFFF,
    @ColumnInfo("onTertiaryFixedVariant") val onTertiaryFixedVariant: Long = 0xFFF0F0F0,
)
