package eu.tvato.lempie.ui.theme

import androidx.compose.ui.graphics.Color

// Dark theme
val primaryDark = Color(0xFFFF0000)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF000000)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val inversePrimaryDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFF9800)   //Color(0xFF0064FA)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF333333)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFF555555)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFFFFC107)
val onTertiaryContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF181818)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFFEA5050)
val onSurfaceVariantDark = Color(0xFFF0F0F0)
val surfaceTintDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFFFFFF)
val inverseOnSurfaceDark = Color(0xFF8F8F8F)

val errorDark = Color(0xFFFF0000)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF000000)
val onErrorContainerDark = Color(0xFFFFFFFF)

val outlineDark = Color(0xFF880000)
val outlineVariantDark = Color(0xFFF08500)

val scrimDark = Color(0x44FF0000)

val surfaceBrightDark = Color(0xFF505050)
val surfaceContainerDark = Color(0xFF303030)
val surfaceContainerHighDark = Color(0xFF505050)
val surfaceContainerHighestDark = Color(0xFF535353)
val surfaceContainerLowDark = Color(0xFF121212)
val surfaceContainerLowestDark = Color(0xFF050505)
val surfaceDimDark = Color(0xFF000000)

val primaryFixedDark = Color(0xFF050505)
val primaryFixedDimDark = Color(0xFF000000)
val onPrimaryFixedDark = Color(0xFFFFFFFF)
val onPrimaryFixedVariantDark = Color(0xFFF0F0F0)

val secondaryFixedDark = Color(0xFF303030)
val secondaryFixedDimDark = Color(0xFF060606)
val onSecondaryFixedDark = Color(0xFFFFFFFF)
val onSecondaryFixedVariantDark = Color(0xFFF0F0F0)

val tertiaryFixedDark = Color(0xFF5F5F5F)
val tertiaryFixedDimDark = Color(0xFF353535)
val onTertiaryFixedDark = Color(0xFFFFFFFF)
val onTertiaryFixedVariantDark = Color(0xFFF0F0F0)


// Light theme
val primaryLight = Color(0xFF445E91)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E2FF)
val onPrimaryContainerLight = Color(0xFF2B4678)
val secondaryLight = Color(0xFF575E71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBE2F9)
val onSecondaryContainerLight = Color(0xFF3F4759)
val tertiaryLight = Color(0xFF715573)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFBD7FC)
val onTertiaryContainerLight = Color(0xFF583E5B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFADC6FF)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)


// Generated Dark
val primaryDarkGen = Color(0xFFFFB4A8)
val onPrimaryDarkGen = Color(0xFF690100)
val primaryContainerDarkGen = Color(0xFF303030)
val onPrimaryContainerDarkGen = Color(0xFF360000)
val secondaryDarkGen = Color(0xFFFFB77B)
val onSecondaryDarkGen = Color(0xFF4D2700)
val secondaryContainerDarkGen = Color(0xFFD97800)
val onSecondaryContainerDarkGen = Color(0xFF432100)
val tertiaryDarkGen = Color(0xFFFFE2A6)
val onTertiaryDarkGen = Color(0xFF3F2E00)
val tertiaryContainerDarkGen = Color(0xFFFCC000)
val onTertiaryContainerDarkGen = Color(0xFF6B5000)
val errorDarkGen = Color(0xFFFFB4AB)
val onErrorDarkGen = Color(0xFF690005)
val errorContainerDarkGen = Color(0xFF93000A)
val onErrorContainerDarkGen = Color(0xFFFFDAD6)
val backgroundDarkGen = Color(0xFF000000)
val onBackgroundDarkGen = Color(0xFFFFDAD4)
val surfaceDarkGen = Color(0xFF131313)
val onSurfaceDarkGen = Color(0xFFE2E2E2)
val surfaceVariantDarkGen = Color(0xFF444748)
val onSurfaceVariantDarkGen = Color(0xFFC4C7C7)
val outlineDarkGen = Color(0xFF8E9192)
val outlineVariantDarkGen = Color(0xFF444748)
val scrimDarkGen = Color(0xFF000000)
val inverseSurfaceDarkGen = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkGen = Color(0xFF303030)
val inversePrimaryDarkGen = Color(0xFFC00100)
val surfaceDimDarkGen = Color(0xFF131313)
val surfaceBrightDarkGen = Color(0xFF393939)
val surfaceContainerLowestDarkGen = Color(0xFF0E0E0E)
val surfaceContainerLowDarkGen = Color(0xFF1B1B1B)
val surfaceContainerDarkGen = Color(0xFF1F1F1F)
val surfaceContainerHighDarkGen = Color(0xFF2A2A2A)
val surfaceContainerHighestDarkGen = Color(0xFF353535)

val primaryDarkMediumContrast = Color(0xFFFFD2CB)
val onPrimaryDarkMediumContrast = Color(0xFF540000)
val primaryContainerDarkMediumContrast = Color(0xFFFF5540)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFD4B4)
val onSecondaryDarkMediumContrast = Color(0xFF3D1E00)
val secondaryContainerDarkMediumContrast = Color(0xFFD97800)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFE2A6)
val onTertiaryDarkMediumContrast = Color(0xFF392900)
val tertiaryContainerDarkMediumContrast = Color(0xFFFCC000)
val onTertiaryContainerDarkMediumContrast = Color(0xFF483500)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF210E0B)
val onBackgroundDarkMediumContrast = Color(0xFFFFDAD4)
val surfaceDarkMediumContrast = Color(0xFF131313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444748)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDADDDD)
val outlineDarkMediumContrast = Color(0xFFAFB2B3)
val outlineVariantDarkMediumContrast = Color(0xFF8E9191)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF950100)
val surfaceDimDarkMediumContrast = Color(0xFF131313)
val surfaceBrightDarkMediumContrast = Color(0xFF444444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF282828)
val surfaceContainerHighDarkMediumContrast = Color(0xFF323232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E3E)

val primaryDarkHighContrast = Color(0xFFFFECE9)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFAEA1)
val onPrimaryContainerDarkHighContrast = Color(0xFF220000)
val secondaryDarkHighContrast = Color(0xFFFFEDE1)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFB270)
val onSecondaryContainerDarkHighContrast = Color(0xFF170700)
val tertiaryDarkHighContrast = Color(0xFFFFEED0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFCC000)
val onTertiaryContainerDarkHighContrast = Color(0xFF1C1300)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF210E0B)
val onBackgroundDarkHighContrast = Color(0xFFFFDAD4)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444748)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEF0F1)
val outlineVariantDarkHighContrast = Color(0xFFC0C3C4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF950100)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF505050)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F1F)
val surfaceContainerDarkHighContrast = Color(0xFF303030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474747)